CREATE TABLE IF NOT EXISTS personas (
	ID INTEGER NOT NULL PRIMARY KEY,
	TIPO_DOCUMENTO INTEGER NOT NULL DEFAULT 1,
	LETRAS VARCHAR(5),
	TELF1 VARCHAR(12),
	TELF2 VARCHAR(12),
	DOMICILIO VARCHAR(50),
	CP INTEGER(5),
	POBLACION VARCHAR(50),
	FECHA_ALTA DATE DEFAULT CURRENT_DATE,
	LAST_UPDATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	COMENTARIOS LONGTEXT DEFAULT 'Sin comentarios',
	);
