CREATE TABLE IF NOT EXISTS cuentas (
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	REF_CLIENTE VARCHAR(11) NOT NULL,
	FECHA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	DESCRIPCION VARCHAR(50) NOT NULL DEFAULT 'Descripcion',
	DEBE double(10,2) NOT NULL DEFAULT 0,
	HABER double(10,2) NOT NULL DEFAULT 0
	);
	
INSERT INTO cuentas (REF_CLIENTE, DESCRIPCION, DEBE, HABER)
VALUES (1, 'Pago en efectivo', 150.50, 0);